/**
 * Writes design-system/COMPONENTS.md: the generated inventory of every primitive and component
 * with its description and props (`npm run components:md`). CI fails when it is stale.
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { componentFolders, DS_ROOT, readComponentDoc } from './component-folders';

const escape = (text: string): string => text.replace(/\|/g, '\\|');

function render(): string {
  const lines = [
    // First line: the file-length check exempts a file whose first line names its generator.
    '<!-- GENERATED by `npm run components:md` from the component sources. Do not edit. -->',
    '',
    '# Design-system inventory',
    '',
    'Read this before building any UI (ADR 0011, `.claude/skills/add-ui-component`): if a',
    'component or a composition of them does the job, use it; otherwise add a generic one.',
    'Import everything from `@algotrade/ui`.',
    '',
  ];
  const folders = componentFolders();
  for (const kind of ['primitives', 'components'] as const) {
    const inKind = folders.filter((f) => f.kind === kind);
    lines.push(`## ${kind === 'primitives' ? 'Primitives' : 'Components'}`, '');
    if (inKind.length === 0) {
      lines.push('None yet (built after the mockups are approved).', '');
      continue;
    }
    for (const folder of inKind) {
      const doc = readComponentDoc(folder);
      lines.push(
        `### ${folder.name}`,
        '',
        doc.description || '(no description)',
        '',
        `Source: \`${folder.rel}\``,
        '',
      );
      lines.push('| Prop | Type | Required | Description |', '|---|---|---|---|');
      for (const prop of doc.props) {
        lines.push(
          `| \`${escape(prop.name)}\` | \`${escape(prop.type)}\` | ${prop.optional ? 'no' : 'yes'} | ${escape(prop.doc)} |`,
        );
      }
      lines.push('');
    }
  }
  return lines.join('\n');
}

const target = join(DS_ROOT, 'COMPONENTS.md');
writeFileSync(target, render());
console.log(`components: wrote ${target}`);
