/**
 * Generates the typed API schema (src/shared/api/generated/schema.ts) from the FastAPI OpenAPI
 * document the API app commits, apps/api/openapi.json (`npm run api:generate`). When the API
 * changes, regenerate here in the same PR: CI regenerates and fails on any diff.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import openapiTS, { astToString } from 'openapi-typescript';

const source = fileURLToPath(new URL('../../api/openapi.json', import.meta.url));
const target = fileURLToPath(new URL('../src/shared/api/generated/schema.ts', import.meta.url));

const document = JSON.parse(readFileSync(source, 'utf8')) as Parameters<typeof openapiTS>[0];
const ast = await openapiTS(document, { alphabetize: true });
const header =
  '/* GENERATED by `npm run api:generate` from apps/api/openapi.json. Do not edit. */\n/* eslint-disable */\n';
writeFileSync(target, header + astToString(ast));
console.log(`api: wrote ${target} from apps/api/openapi.json`);
