/**
 * Codegen hook: puts the generator's name on the first line of each generated GraphQL file, so
 * `scripts/check_file_length.py` exempts it (generated files are regenerated, never edited).
 */
import { readFileSync, writeFileSync } from 'node:fs';

const MARK = '/* GENERATED by graphql-codegen (npm run api:generate). Do not edit. */';

for (const file of process.argv.slice(2)) {
  const text = readFileSync(file, 'utf8');
  if (!text.startsWith(MARK)) writeFileSync(file, `${MARK}\n${text}`);
}
