"""Render ``docs/edges.md`` from the site's edge documents (ADR 0053 decision 1): a table of
every edge with its status, then one section per edge with its thesis, outcome, schedule,
universe, implementations, the nine quality-bar answers and the sources. ``make features-doc``
writes it; a test keeps the committed page up to date."""

from collections.abc import Iterable

from algotrade.config.edges.document import EVENT_CLASSES, STATUSES, Edge, Outcome, event_class
from algotrade.core.model.predicates import Group, Rule

PATH = "docs/edges.md"
SOURCE = "config/site/edges/"
QUESTIONS = {
    "mechanism": "Mechanism",
    "persistence": "Persistence",
    "outcome": "Outcome",
    "trigger_timing": "Trigger timing",
    "replication": "Faithful replication",
    "expected_size": "Expected size and sample",
    "capacity_costs": "Capacity and costs",
    "failure_modes": "Failure modes and retirement",
    "decoys": "Decoys",
}

HEADER = f"""# Edges

Generated by `make features-doc` from `{SOURCE}` (one document per edge); edit
those, not this page. An edge is a written hypothesis with the reason it persists, a defined
outcome and the screeners that implement it; the harness scores each screener point in time
against the stored outcomes (ADR 0053, plan [edges-plan.md](edges-plan.md)). A document is
accepted only when it answers the plan's nine quality-bar questions; rejected and blocked
candidates stay on file with the reason, so the same idea is not filed twice.
"""


def render(edges: Iterable[Edge]) -> str:
    found = sorted(edges, key=lambda e: (STATUSES.index(e.status), e.id))
    lines = [HEADER, "| Edge | Status | Schedule | Outcome | Screeners |", "|---|---|---|---|---|"]
    lines += [
        f"| {e.name} (`{e.id}`) | {e.status} | {_schedule(e.schedule, brief=True)} "
        f"| {_outcome(e.outcome, e.event_class is not None)} "
        f"| {_ids(e.screeners)} |"
        for e in found
    ]
    for edge in found:
        lines += ["", *_section(edge)]
    return "\n".join(lines) + "\n"


def _section(e: Edge) -> list[str]:
    universe = f"preset `{e.universe}`" if isinstance(e.universe, str) else _group(e.universe.where)
    lines = [
        f"## {e.name} (`{e.id}`)",
        "",
        f"**Status:** {e.status}. **Thesis:** {e.thesis}",
        "",
    ]
    if e.rejection_reason:
        lines += [f"**Why {e.status}:** {e.rejection_reason}", ""]
    lines += [
        f"- **Outcome:** {_outcome(e.outcome, e.event_class is not None)}",
        f"- **Schedule:** {_schedule(e.schedule, brief=False)}",
        f"- **Universe:** {universe}",
        f"- **Top K:** {'all qualified names' if e.top_k is None else e.top_k}",
        f"- **Screeners:** {_ids(e.screeners)}",
        f"- **Baselines:** {_ids(e.baselines)}",
    ]
    if e.frozen_from:
        lines.append(f"- **Frozen period:** from {e.frozen_from.isoformat()}")
    if e.notes:
        lines.append(f"- **Notes:** {e.notes}")
    lines += ["", "**Quality bar**", ""]
    lines += [
        f"{i}. **{QUESTIONS[key]}:** {answer or '(not answered)'}"
        for i, (key, answer) in enumerate(e.answers, 1)
    ]
    lines += ["", "**Sources**", ""]
    lines += [f"- {s.title}" + (f" <{s.url}>" if s.url else "") for s in e.sources]
    return lines


def _outcome(o: Outcome, event: bool) -> str:
    horizons = ", ".join(str(h) for h in o.horizon_sessions)
    plural = "" if o.horizon_sessions == (1,) else "s"
    parts = [o.kind.replace("_", " "), f"over {horizons} session{plural}"]
    if o.benchmark != "none":
        parts.append(f"vs {o.benchmark}")
    if event and o.start_offset_sessions:
        parts.append(f"starting {o.start_offset_sessions:+d} sessions from the event")
    elif not event:
        n = o.start_offset_sessions
        parts.append(f"entered {n} session{'' if n == 1 else 's'} after the decision session")
    if o.target is not None:
        parts.append(f"hit when {o.measure} is {o.direction} {o.target:g}")
    if o.max_drawdown is not None:
        parts.append(f"max drawdown {o.max_drawdown:g}")
    if o.cost_bps is not None:
        parts.append(f"costs {o.cost_bps:g} bps")
    return ", ".join(parts)


def _schedule(schedule: str, brief: bool) -> str:
    event = event_class(schedule)
    if event is not None:
        return f"on each `{event}`" + ("" if brief else f" ({EVENT_CLASSES[event]})")
    return schedule.replace("_", " ")


def _ids(ids: tuple[str, ...]) -> str:
    return ", ".join(f"`{i}`" for i in ids) if ids else "none yet"


def _group(group: Group) -> str:
    parts = [
        f"`{c.describe()}`" if isinstance(c, Rule) else f"({_group(c)})" for c in group.children
    ]
    if group.kind == "not":
        return f"not {parts[0]}"
    return f" {'and' if group.kind == 'all' else 'or'} ".join(parts)
