"""The committed golden CSV files: manifest, checksums, reading and writing.

Layout (reviewable in PRs; never edited by hand, regenerated by ``golden build``)::

    <root>/manifest.json   {"datasets": {name: {description, tags, files: {SYMBOL: sha256}}}}
    <root>/<dataset>/<SYMBOL>.csv   timestamp,open,high,low,close,volume
"""

import hashlib
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pandas as pd

from algotrade.core.errors import ConfigurationError, DataValidationError
from algotrade.core.series import FIELDS, PriceSeries
from algotrade.storage.schemas import bar_problems

MANIFEST = "manifest.json"
TIMESTAMP = "timestamp"


def sha256_of(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


@dataclass(frozen=True)
class GoldenDataset:
    name: str
    description: str
    symbols: tuple[str, ...]
    checksums: dict[str, str]
    tags: tuple[str, ...]


class GoldenFiles:
    def __init__(self, root: Path) -> None:
        self.root = root

    def manifest(self) -> dict[str, GoldenDataset]:
        path = self.root / MANIFEST
        if not path.exists():
            raise ConfigurationError(f"No golden manifest at {path}")
        raw: dict[str, Any] = json.loads(path.read_text())
        return {
            name: GoldenDataset(name, entry["description"], tuple(entry["files"]),
                                dict(entry["files"]), tuple(entry.get("tags", [])))
            for name, entry in sorted(raw["datasets"].items())
        }  # fmt: skip

    def verify(self) -> list[str]:
        """Integrity problems; an empty list means every checksum matches."""
        problems: list[str] = []
        for ds in self.manifest().values():
            for symbol, expected in ds.checksums.items():
                path = self.root / ds.name / f"{symbol}.csv"
                if not path.exists():
                    problems.append(f"{path}: missing")
                elif sha256_of(path) != expected:
                    problems.append(f"{path}: checksum mismatch")
        return problems

    def read(self, name: str, symbol: str) -> pd.DataFrame:
        """One symbol's bars, validated, with a UTC ``ts`` column."""
        path = self.root / name / f"{symbol}.csv"
        frame = pd.read_csv(path)
        ts = pd.to_datetime(frame.pop(TIMESTAMP), utc=True)
        problems = bar_problems(frame)
        if not ts.is_monotonic_increasing or ts.duplicated().any():
            problems.append("timestamps not strictly increasing")
        if problems:
            raise DataValidationError(str(path), problems)
        frame.insert(0, "ts", ts)
        return frame

    def write(
        self, name: str, description: str, series: dict[str, PriceSeries], tags: tuple[str, ...]
    ) -> None:
        directory = self.root / name
        directory.mkdir(parents=True, exist_ok=True)
        files: dict[str, str] = {}
        for symbol, s in sorted(series.items()):
            frame = pd.DataFrame({TIMESTAMP: pd.to_datetime(s.timestamps, utc=True),
                                  **{f: s.field(f) for f in FIELDS}})  # fmt: skip
            problems = bar_problems(frame)
            if problems:
                raise DataValidationError(f"{name}/{symbol}", problems)
            path = directory / f"{symbol}.csv"
            frame.to_csv(path, index=False, float_format="%.6f", date_format="%Y-%m-%dT%H:%M:%SZ")
            files[symbol] = sha256_of(path)
        self._update_manifest(
            name, {"description": description, "tags": list(tags), "files": files}
        )

    def _update_manifest(self, name: str, entry: dict[str, Any]) -> None:
        path = self.root / MANIFEST
        raw: dict[str, Any] = json.loads(path.read_text()) if path.exists() else {"datasets": {}}
        raw["datasets"][name] = entry
        raw["datasets"] = dict(sorted(raw["datasets"].items()))
        path.write_text(json.dumps(raw, indent=2) + "\n")
