"""Structural rules the codebase must keep. These complement import-linter contracts."""

import ast
import hashlib
import re
import subprocess
import sys
import tomllib
from pathlib import Path

from tests.conftest import REPO_ROOT

SRC = REPO_ROOT / "src" / "algotrade"
LAYERS = sorted(p.name for p in SRC.iterdir() if p.is_dir() and not p.name.startswith("_"))


def test_file_length_limit() -> None:
    proc = subprocess.run(
        [sys.executable, "scripts/check_file_length.py"],
        cwd=REPO_ROOT, capture_output=True, text=True, check=False,
    )  # fmt: skip
    assert proc.returncode == 0, proc.stdout


def test_every_layer_has_unit_tests() -> None:
    missing = [
        layer for layer in LAYERS
        if layer != "cli" and not any((REPO_ROOT / "tests" / "unit" / layer).rglob("test_*.py"))
    ]  # fmt: skip
    assert not missing, f"layers without unit tests: {missing}"


def test_every_layer_is_documented() -> None:
    architecture = (REPO_ROOT / "docs" / "architecture.md").read_text()
    undocumented = [layer for layer in LAYERS if f"`{layer}/`" not in architecture]
    assert not undocumented, f"add these layers to docs/architecture.md: {undocumented}"


def test_every_module_has_a_docstring() -> None:
    missing = []
    for path in SRC.rglob("*.py"):
        if path.name == "__main__.py":
            continue
        if ast.get_docstring(ast.parse(path.read_text())) is None:
            missing.append(str(path.relative_to(REPO_ROOT)))
    assert not missing, f"modules need a docstring explaining their responsibility: {missing}"


# ADR 0018: equity ids come from the id rule (core) or the symbol resolver, never ad hoc.
_ADHOC_ID = re.compile(r"""f?["']EQ:|AssetClass\.EQUITY\s*,|\bequity_id\(""")
_ID_OWNERS = {
    "src/algotrade/core/model/instruments.py",
    "src/algotrade/data/resolver.py",
    "apps/ingestion/algotrade_ingestion/tasks/reference/instrument_ids.py",
}


def test_equity_ids_are_built_only_by_the_id_rule_and_resolver() -> None:
    offenders = []
    for root in (REPO_ROOT / "src", REPO_ROOT / "libs", REPO_ROOT / "apps"):
        for path in root.rglob("*.py"):
            rel = path.relative_to(REPO_ROOT).as_posix()
            if rel in _ID_OWNERS or ".venv" in rel or "node_modules" in rel:
                continue
            code = [
                line for line in path.read_text().splitlines() if not line.lstrip().startswith("#")
            ]
            offenders += [f"{rel}: {line.strip()}" for line in code if _ADHOC_ID.search(line)]
    assert not offenders, f"resolve symbols with SymbolResolver (ADR 0018): {offenders}"


def test_scripts_flag_long_files(tmp_path: Path) -> None:
    long_file = tmp_path / "big.py"
    long_file.write_text("x = 1\n" * 1001)
    proc = subprocess.run(
        [sys.executable, "scripts/check_file_length.py", str(long_file)],
        cwd=REPO_ROOT, capture_output=True, text=True, check=False,
    )  # fmt: skip
    assert proc.returncode == 1
    assert "1001 lines" in proc.stdout


def test_generated_files_are_exempt_from_the_length_limit(tmp_path: Path) -> None:
    generated = tmp_path / "schema.ts"
    header = "/* GENERATED by `npm run api:generate`. Do not edit. */\n"
    generated.write_text(header + "x;\n" * 1001)
    proc = subprocess.run(
        [sys.executable, "scripts/check_file_length.py", str(generated)],
        cwd=REPO_ROOT, capture_output=True, text=True, check=False,
    )  # fmt: skip
    assert proc.returncode == 0, proc.stdout


# ----------------------------------------------------------------------------- preset versions
PRESETS = Path("config/site/presets/screeners")
PRESET_LOCK = Path("architecture/preset_versions.toml")


def preset_version_problems(root: Path) -> list[str]:
    """Why the site rule-screen preset versions under ``root`` break immutability (ADR 0029):
    an unlisted or changed version file, a listed one gone, or a file whose ``id`` /
    ``version`` disagree with its path."""
    lock = tomllib.loads((root / PRESET_LOCK).read_text()).get("versions", {})
    found = {
        p.relative_to(root / PRESETS).as_posix(): p
        for p in sorted((root / PRESETS).glob("*/*.toml"))
    }
    problems = [f"{name}: listed in {PRESET_LOCK} but gone" for name in lock if name not in found]
    for name, path in found.items():
        match = re.fullmatch(r"([a-z0-9_-]{1,64})/v([1-9][0-9]*)\.toml", name)
        if match is None:
            problems.append(f"{name}: a preset folder holds only v<N>.toml files")
            continue
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        if name not in lock:
            problems.append(f'{name}: add `"{name}" = "{digest}"` to {PRESET_LOCK}')
        elif lock[name] != digest:
            problems.append(f"{name}: changed; versions are immutable: add v<N+1> instead")
        doc = tomllib.loads(path.read_text())
        if (doc.get("id"), doc.get("version")) != (match[1], int(match[2])):
            problems.append(f"{name}: id / version must be {match[1]!r} / {match[2]}")
    return problems


def test_site_preset_versions_are_immutable() -> None:
    assert preset_version_problems(REPO_ROOT) == []


def test_preset_version_check_catches_edits(tmp_path: Path) -> None:
    (tmp_path / PRESET_LOCK).parent.mkdir()
    folder = tmp_path / PRESETS / "vrp"
    folder.mkdir(parents=True)
    v1 = folder / "v1.toml"
    v1.write_text('id = "vrp"\nversion = 1\n')
    digest = hashlib.sha256(v1.read_bytes()).hexdigest()
    (tmp_path / PRESET_LOCK).write_text(f'[versions]\n"vrp/v1.toml" = "{digest}"\n')
    assert preset_version_problems(tmp_path) == []
    v1.write_text('id = "vrp"\nversion = 1\nx = 2\n')
    (folder / "v2.toml").write_text('id = "vrp"\nversion = 3\n')
    (folder / "draft.toml").write_text("")
    problems = " | ".join(preset_version_problems(tmp_path))
    assert "vrp/v1.toml: changed" in problems
    assert "vrp/v2.toml: add" in problems and "version must be" in problems
    assert "only v<N>.toml" in problems
    v1.unlink()
    assert any("gone" in p for p in preset_version_problems(tmp_path))
