/**
 * Renders the typed tokens as CSS custom properties (the generated `tokens.css`).
 *
 * Themes (dark-first): `:root` is dark; `[data-theme='light']` is light; `[data-theme='system']`
 * follows `prefers-color-scheme`. Density: `[data-density='comfortable']` overrides the compact
 * default; `@media (pointer: coarse)` raises control and row heights to the `touch` floor. Up / down: `[data-updown='cvd']` switches to the colour-blind-safe pair.
 * Run `npm run tokens` after editing a token source; CI fails if tokens.css is stale.
 */
import { colorRoles, dark, light, type Palette } from './color';
import { density, touch, type Density } from './density';
import { zIndex } from './layers';
import { duration, easing } from './motion';
import { borderWidth, focusRing, radius } from './shape';
import { size, space, spaceName, type Space } from './space';
import { fontFamily, fontFeatures, fontSize, fontWeight } from './typography';

type Vars = [name: string, value: string | number][];

const px = (n: number): string => (n === 0 ? '0' : `${n}px`);

function colorVars(palette: Palette, upDown: 'standard' | 'cvd'): Vars {
  return colorRoles(palette, upDown).map(([name, value]) => [`--color-${name}`, value]);
}

function upDownVars(palette: Palette): Vars {
  return [
    ['--color-up', palette.up.cvd],
    ['--color-down', palette.down.cvd],
  ];
}

function densityVars(d: Density): Vars {
  return [
    ['--density-control-height', px(d.controlHeight)],
    ['--density-row-height', px(d.rowHeight)],
    ['--density-cell-padding-x', px(d.cellPaddingX)],
    ['--density-cell-padding-y', px(d.cellPaddingY)],
    ['--density-panel-padding-x', px(d.panelPaddingX)],
    ['--density-panel-padding-y', px(d.panelPaddingY)],
    ['--density-gap', px(d.gap)],
  ];
}

function staticVars(): Vars {
  return [
    ['--font-sans', fontFamily.sans],
    ['--font-mono', fontFamily.mono],
    ['--font-features', fontFeatures],
    ...Object.entries(fontSize).flatMap(([k, v]): Vars => [
      [`--font-size-${k}`, px(v.size)],
      [`--line-height-${k}`, px(v.lineHeight)],
    ]),
    ...Object.entries(fontWeight).map(([k, v]): [string, number] => [`--font-weight-${k}`, v]),
    ...(Object.keys(space) as unknown as Space[]).map((k): [string, string] => [
      `--space-${spaceName(k)}`,
      px(space[k]),
    ]),
    ...Object.entries(size).map(([k, v]): [string, string] => [`--size-${k}`, px(v)]),
    ...Object.entries(radius).map(([k, v]): [string, string] => [`--radius-${k}`, px(v)]),
    ...Object.entries(borderWidth).map(([k, v]): [string, string] => [
      `--border-width-${k}`,
      px(v),
    ]),
    ['--focus-ring-width', px(focusRing.width)],
    ['--focus-ring-offset', px(focusRing.offset)],
    ...Object.entries(duration).map(([k, v]): [string, string] => [`--duration-${k}`, `${v}ms`]),
    ...Object.entries(easing).map(([k, v]): [string, string] => [`--easing-${k}`, v]),
    ...Object.entries(zIndex).map(([k, v]): [string, number] => [`--z-${k}`, v]),
  ];
}

function block(selector: string, vars: Vars, indent = ''): string {
  const body = vars.map(([n, v]) => `${indent}  ${n}: ${v};`).join('\n');
  return `${indent}${selector} {\n${body}\n${indent}}`;
}

const LIGHT = ":root[data-theme='light']";
const SYSTEM = ":root[data-theme='system']";

/** The full generated stylesheet. */
export function renderTokensCss(): string {
  const header =
    '/* GENERATED by `npm run tokens` from design-system/tokens/*.ts. Do not edit. FINAL tokens (approved mockups 2026-10-03, ADR 0011). */';
  const lightVars: Vars = [...colorVars(light, 'standard'), ['color-scheme', 'light']];
  const blocks = [
    header,
    block(':root', [
      ...staticVars(),
      ...densityVars(density.compact),
      ...colorVars(dark, 'standard'),
      ['color-scheme', 'dark'],
    ]),
    block(":root[data-updown='cvd']", upDownVars(dark)),
    block(LIGHT, lightVars),
    block(`${LIGHT}[data-updown='cvd']`, upDownVars(light)),
    `@media (prefers-color-scheme: light) {\n${block(SYSTEM, lightVars, '  ')}\n\n${block(
      `${SYSTEM}[data-updown='cvd']`,
      upDownVars(light),
      '  ',
    )}\n}`,
    block(":root[data-density='comfortable']", densityVars(density.comfortable)),
    `@media (pointer: coarse) {\n${block(
      ':root',
      [
        ['--density-control-height', px(touch.controlHeight)],
        ['--density-row-height', px(touch.rowHeight)],
        ['--density-cell-padding-y', px(touch.cellPaddingY)],
      ],
      '  ',
    )}\n}`,
    `@media (prefers-reduced-motion: reduce) {\n${block(
      ':root',
      Object.keys(duration).map((k): [string, string] => [`--duration-${k}`, '0ms']),
      '  ',
    )}\n}`,
  ];
  return `${blocks.join('\n\n')}\n`;
}
