/**
 * Renders the typed tokens as CSS custom properties (the generated `tokens.css`).
 *
 * Themes: `:root` is light; `[data-theme='dark']` is dark; with no explicit theme the
 * system preference decides. Density: `[data-density='comfortable']` overrides the compact
 * default. Up / down: `[data-updown='cvd']` switches to the colour-blind-safe pair.
 * Run `npm run tokens` after editing a token source; CI fails if tokens.css is stale.
 */
import { dark, light, roles, type Palette } from './color';
import { density, type Density } from './density';
import { zIndex } from './layers';
import { duration, easing } from './motion';
import { borderWidth, focusRing, radius } from './shape';
import { space, spaceName, type Space } from './space';
import { fontFamily, fontFeatures, fontSize, fontWeight } from './typography';

type Vars = [name: string, value: string | number][];

const px = (n: number): string => (n === 0 ? '0' : `${n}px`);

function resolve(palette: Palette, path: string): string {
  const [head, key] = path.split('.') as [keyof Palette, string | undefined];
  if (head === 'gray') return palette.gray[Number(key) - 1] as string;
  const value = palette[head];
  if (typeof value === 'string') return value;
  return (value as Record<string, string>)[key ?? ''] as string;
}

function colorVars(palette: Palette, updown: 'standard' | 'cvd'): Vars {
  const steps: Vars = palette.gray.map((hex, i) => [`--color-gray-${i + 1}`, hex]);
  const semantic: Vars = Object.entries(roles).map(([role, path]) => [
    `--color-${role}`,
    resolve(palette, path),
  ]);
  return [
    ...steps,
    ...semantic,
    ['--color-up', palette.up[updown]],
    ['--color-down', palette.down[updown]],
  ];
}

function densityVars(d: Density): Vars {
  return [
    ['--density-control-height', px(d.controlHeight)],
    ['--density-row-height', px(d.rowHeight)],
    ['--density-cell-padding-x', px(d.cellPaddingX)],
    ['--density-cell-padding-y', px(d.cellPaddingY)],
    ['--density-gap', px(d.gap)],
  ];
}

function staticVars(): Vars {
  return [
    ['--font-sans', fontFamily.sans],
    ['--font-mono', fontFamily.mono],
    ['--font-features', fontFeatures],
    ...Object.entries(fontSize).flatMap(([k, v]): Vars => [
      [`--font-size-${k}`, px(v.size)],
      [`--line-height-${k}`, px(v.lineHeight)],
    ]),
    ...Object.entries(fontWeight).map(([k, v]): [string, number] => [`--font-weight-${k}`, v]),
    ...(Object.keys(space) as unknown as Space[]).map((k): [string, string] => [
      `--space-${spaceName(k)}`,
      px(space[k]),
    ]),
    ...Object.entries(radius).map(([k, v]): [string, string] => [`--radius-${k}`, px(v)]),
    ...Object.entries(borderWidth).map(([k, v]): [string, string] => [
      `--border-width-${k}`,
      px(v),
    ]),
    ['--focus-ring-width', px(focusRing.width)],
    ['--focus-ring-offset', px(focusRing.offset)],
    ...Object.entries(duration).map(([k, v]): [string, string] => [`--duration-${k}`, `${v}ms`]),
    ...Object.entries(easing).map(([k, v]): [string, string] => [`--easing-${k}`, v]),
    ...Object.entries(zIndex).map(([k, v]): [string, number] => [`--z-${k}`, v]),
  ];
}

function block(selector: string, vars: Vars, indent = ''): string {
  const body = vars.map(([n, v]) => `${indent}  ${n}: ${v};`).join('\n');
  return `${indent}${selector} {\n${body}\n${indent}}`;
}

/** The full generated stylesheet. */
export function renderTokensCss(): string {
  const header =
    '/* GENERATED by `npm run tokens` from design-system/tokens/*.ts. Do not edit. DRAFT tokens (ADR 0011). */';
  return [
    header,
    block(':root', [
      ...staticVars(),
      ...densityVars(density.compact),
      ...colorVars(light, 'standard'),
      ['color-scheme', 'light'],
    ]),
    block(":root[data-updown='cvd']", [
      ['--color-up', light.up.cvd],
      ['--color-down', light.down.cvd],
    ]),
    `@media (prefers-color-scheme: dark) {\n${block(":root:not([data-theme='light'])", [...colorVars(dark, 'standard'), ['color-scheme', 'dark']], '  ')}\n${block(
      ":root:not([data-theme='light'])[data-updown='cvd']",
      [
        ['--color-up', dark.up.cvd],
        ['--color-down', dark.down.cvd],
      ],
      '  ',
    )}\n}`,
    block(":root[data-theme='dark']", [...colorVars(dark, 'standard'), ['color-scheme', 'dark']]),
    block(":root[data-theme='dark'][data-updown='cvd']", [
      ['--color-up', dark.up.cvd],
      ['--color-down', dark.down.cvd],
    ]),
    block(":root[data-density='comfortable']", densityVars(density.comfortable)),
    `@media (prefers-reduced-motion: reduce) {\n${block(
      ':root',
      Object.keys(duration).map((k): [string, string] => [`--duration-${k}`, '0ms']),
      '  ',
    )}\n}`,
    '',
  ].join('\n\n');
}
