/**
 * Test builders for the regime entity (exported for widget and page tests): a `Regime` with three indicator cards (two slow, one
 * fast; one changed; two cite the same link) and the same regime as an UNKNOWN session.
 */
import type { Regime } from './regime';

const NO_UNKNOWN = null;

export function regimeFixture(overrides: Partial<Regime> = {}): Regime {
  return {
    session: '2026-10-02',
    label: 'CAUTION',
    headline: '1 of 3 warning signs is on. The fast signs are quiet.',
    scores: {
      macroRisk: {
        value: 62,
        unknown: NO_UNKNOWN,
        feature: 'market.regime@v2.macro_risk',
        coverageFeature: 'market.regime@v2.macro_coverage',
        threshold: 50,
      },
      marketStress: {
        value: 18,
        unknown: NO_UNKNOWN,
        feature: 'market.regime@v2.market_stress',
        coverageFeature: 'market.regime@v2.market_coverage',
        threshold: 50,
      },
      fragility: {
        value: 40,
        unknown: NO_UNKNOWN,
        feature: 'market.regime@v2.fragility',
        coverageFeature: null,
        threshold: null,
      },
    },
    sizing: {
      label: 'CAUTION',
      multiplier: 0.75,
      enabled: true,
      multipliers: [
        { label: 'CALM', multiplier: 1 },
        { label: 'CAUTION', multiplier: 0.75 },
        { label: 'STRESS', multiplier: 0.5 },
        { label: 'CRISIS', multiplier: 0.25 },
      ],
      unknownMultiplier: 0,
      screeners: [
        { screenerId: 'momentum', name: 'Momentum', enabled: true, pauseIn: ['CRISIS'] },
        {
          screenerId: 'vrp_scanner',
          name: 'VRP scanner',
          enabled: true,
          pauseIn: ['STRESS', 'CRISIS'],
        },
        { screenerId: 'quiet', name: 'Quiet', enabled: true, pauseIn: [] },
      ],
    },
    unknownReason: NO_UNKNOWN,
    indicators: [
      {
        key: 'curve_10y3m',
        pace: 'slow',
        plainName: 'Is the yield curve inverted?',
        technicalName: '10y minus 3m Treasury spread',
        oneLiner: 'Long rates below short rates.',
        whyItMatters: 'An inverted curve has come before every recent recession.',
        whatOnMeans: 'Banks earn less on lending, so they lend less.',
        before: [
          { episode: '2008', line: 'Inverted for 16 months before the fall.' },
          { episode: '2022', line: 'Inverted for 20 months; no recession followed yet.' },
        ],
        leadTime: '6 to 24 months',
        falseAlarms: 'Few, but it can be early by two years.',
        links: [
          { title: 'FRED: 10y minus 3m spread', url: 'https://fred.stlouisfed.org/series/T10Y3M' },
        ],
        value: 0.42,
        unknown: NO_UNKNOWN,
        format: 'NUMBER',
        status: 'OFF',
        changed: false,
        feature: 'market.regime_indicators@v1.curve_10y3m',
        verdictFeature: 'market.regime_indicators@v1.curve_10y3m_on',
        range: { min: -1.5, max: 3 },
        threshold: 0,
        direction: 'LOWER_IS_RISK',
        how: [
          { text: 'The ', url: null },
          { text: '10-year Treasury yield', url: 'https://fred.stlouisfed.org/series/DGS10' },
          { text: ' minus the 3-month yield, in points.', url: null },
        ],
        sources: [
          {
            label: 'FRED T10Y3M',
            series: 'T10Y3M',
            cadence: 'daily',
            releaseLagDays: 1,
            url: 'https://fred.stlouisfed.org/series/T10Y3M',
            licence: 'public',
            terms: null,
            lastObservation: '2026-10-01',
            vintageDate: '2026-10-02',
            vintageKind: 'lagged',
            firstVintage: null,
            active: true,
          },
        ],
      },
      {
        key: 'nfci',
        pace: 'slow',
        plainName: 'Are financial conditions tight?',
        technicalName: 'Chicago Fed NFCI',
        oneLiner: 'How hard it is to borrow.',
        whyItMatters: 'Tight money slows spending.',
        whatOnMeans: 'Credit is harder to get than usual.',
        before: [],
        leadTime: 'Months',
        falseAlarms: 'Noisy around crises that do not spread.',
        links: [{ title: 'Chicago Fed NFCI', url: 'https://www.chicagofed.org/nfci' }],
        value: 0.3,
        unknown: NO_UNKNOWN,
        format: 'NUMBER',
        status: 'ON',
        changed: true,
        feature: 'market.regime_indicators@v1.nfci',
        verdictFeature: 'market.regime_indicators@v1.nfci_on',
        range: { min: -1, max: 1 },
        threshold: 0.5,
        direction: 'HIGHER_IS_RISK',
        how: [
          { text: 'The Chicago Fed index of ', url: null },
          { text: 'financial conditions', url: 'https://www.chicagofed.org/nfci' },
          { text: ', above zero when money is tighter than average.', url: null },
        ],
        sources: [
          {
            label: 'FRED NFCI',
            series: 'NFCI',
            cadence: 'weekly',
            releaseLagDays: 5,
            url: 'https://fred.stlouisfed.org/series/NFCI',
            licence: 'public',
            terms: null,
            lastObservation: '2026-09-25',
            vintageDate: '2026-10-01',
            vintageKind: 'alfred',
            firstVintage: '1996-05-01',
            active: true,
          },
          {
            label: 'FRED ANFCI',
            series: 'ANFCI',
            cadence: 'weekly',
            releaseLagDays: 5,
            url: 'https://fred.stlouisfed.org/series/ANFCI',
            licence: 'public',
            terms: null,
            lastObservation: null,
            vintageDate: null,
            vintageKind: null,
            firstVintage: null,
            active: false,
          },
        ],
      },
      {
        key: 'vix_term',
        pace: 'fast',
        plainName: 'Is fear rising?',
        technicalName: 'VIX term structure',
        oneLiner: 'Short-term fear above long-term fear.',
        whyItMatters: 'Traders pay up for protection before they sell.',
        whatOnMeans: 'Short-dated volatility is above long-dated volatility.',
        before: [{ episode: '2020', line: 'Flipped a week before the fall.' }],
        leadTime: 'Days',
        falseAlarms: 'Several a year.',
        links: [{ title: 'Chicago Fed NFCI', url: 'https://www.chicagofed.org/nfci' }],
        value: null,
        unknown: { code: 'NO_PARTITION', detail: 'no market row for 2026-10-02' },
        format: 'NUMBER',
        status: 'UNKNOWN',
        changed: null,
        feature: 'market.regime_indicators@v1.vix_term',
        verdictFeature: 'market.regime_indicators@v1.vix_term_on',
        range: { min: 0.7, max: 1.3 },
        threshold: 1,
        direction: 'HIGHER_IS_RISK',
        how: [{ text: 'The VIX divided by the 3-month VIX.', url: null }],
        sources: [],
      },
    ],
    ...overrides,
  };
}

/** The same session before the regime exists in the catalogue (RG3): UNKNOWN with its reason. */
export function unknownRegimeFixture(): Regime {
  const known = regimeFixture();
  return regimeFixture({
    label: 'UNKNOWN',
    headline: 'Not computed yet',
    scores: {
      macroRisk: {
        ...known.scores.macroRisk,
        value: null,
        unknown: { code: 'NOT_IN_CATALOGUE', detail: 'regime not built' },
      },
      marketStress: {
        ...known.scores.marketStress,
        value: null,
        unknown: { code: 'NOT_IN_CATALOGUE', detail: 'regime not built' },
      },
      fragility: {
        ...known.scores.fragility,
        value: null,
        unknown: { code: 'NOT_IN_CATALOGUE', detail: 'regime not built' },
      },
    },
    sizing: { ...known.sizing, label: 'UNKNOWN', multiplier: null },
    unknownReason: { code: 'NOT_IN_CATALOGUE', detail: 'The regime is not in the catalogue yet.' },
    indicators: known.indicators.map((i) => ({
      ...i,
      value: null,
      unknown: { code: 'NOT_IN_CATALOGUE', detail: 'not stored for this session' },
      status: 'UNKNOWN' as const,
      changed: null,
    })),
  });
}
