#!/usr/bin/env python3
"""Write the site's catalogue field names to ``apps/web/src/shared/api/generated/catalogue.ts``
(ADR 0038): ``SITE_FEATURES`` and ``feature('<name>')``, so a site feature name the web app
asks for is checked by ``tsc`` (a typo, or a field that moved, fails the build). A user's own
expression features are checked at request time instead (the ``FeatureName`` scalar).

Run after adding, renaming or retiring a feature (``make features-doc`` time), commit the
result. ``--check`` exits 1 when the committed file is stale (a test does the same in CI).
Usage: python scripts/export_catalogue.py [--check]
"""

import argparse
import sys
from pathlib import Path

from algotrade.services.configs import catalog_of
from algotrade.services.features import site_features
from algotrade.storage.configs.files import FileConfigStore

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "apps" / "web" / "src" / "shared" / "api" / "generated" / "catalogue.ts"

HEADER = """/* GENERATED by scripts/export_catalogue.py from the site catalogue. Do not edit. */
/* eslint-disable */
/**
 * Every site catalogue field (instrument.<column>, rollup.<group>@v<N>.<column>,
 * feature.<name>; docs/data/features.md), so a name the app asks for is checked by tsc.
 */
"""

FOOTER = """
/** A site catalogue field name. */
export type SiteFeature = (typeof SITE_FEATURES)[number];

/** `name`, checked against the site catalogue at compile time (a typo fails tsc). */
export function feature<const N extends SiteFeature>(name: N): N {
  return name;
}
"""


def catalogue_ts() -> str:
    """The file's text: the site's fields in catalogue order."""
    fields = catalog_of(site_features(FileConfigStore(ROOT / "config"))).fields
    names = "".join(f"  '{name}',\n" for name in fields)
    return f"{HEADER}export const SITE_FEATURES = [\n{names}] as const;\n{FOOTER}"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the file is stale")
    args = parser.parse_args()
    text = catalogue_ts()
    if args.check:
        stale = not TARGET.exists() or TARGET.read_text() != text
        print(f"{TARGET}: {'stale; run scripts/export_catalogue.py' if stale else 'up to date'}")
        return 1 if stale else 0
    TARGET.write_text(text)
    print(f"wrote {TARGET}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
