"""Render the field guide page (``docs/data/field-guide.md``) from the site field guide
(``config/site/field_guide/*.toml``, ADR 0041 amended): per theme, each field with how to read
it, a table of the usual criterion per intent, the caveats and the sources; then the
situations that fool several thresholds. ``make features-doc`` writes it next to the
catalogue; ``tests/architecture/test_features.py`` keeps it up to date."""

import json
from collections.abc import Iterable

from algotrade.config.site.field_guide import FieldGuideEntry, FieldGuideSettings, GuideUse

PATH = "docs/data/field-guide.md"
SOURCE = "config/site/field_guide/"

HEADER = f"""# Field guide: how to read the catalogue's fields

Generated by `make features-doc` from `{SOURCE}` (one file per theme); edit those, not this page.
The same guide is shown by the Builder with each field and sent to the text model that drafts
a screen from a sentence (ADR 0041), so a threshold a person reads here is the threshold the
model proposes.

Every field is read the same way: **how to read it** (what low and high mean, in the field's
unit: a decimal field takes 0.10 for 10%), **the criterion per intent** (what a trader wants,
and the rule-screen criterion that expresses it: the operator, the value, the mode and the
near-miss band of [rules.md](../screeners/rules.md); `hard` rejects a miss, `soft` keeps a
near miss as a WATCH or a risk, `score` only ranks), and **when the reading lies**: the
situations in which the number is right and the conclusion is wrong, each with the field
that exposes it. The [situations](#situations-that-fool-several-thresholds) at the end are the
ones that distort many fields at once; a screen that ignores them finds the same false
positives whatever its thresholds. A null never passes a `hard` criterion (missing data never
passes); a field's own catalogue entry ([features.md](features.md)) says when it is null.
"""


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def _value(value: object) -> str:
    return json.dumps(value)


def criterion_text(use: GuideUse) -> str:
    """``op value`` as a person reads it (``is_null`` and ``not_null`` take no value)."""
    if use.op in ("is_null", "not_null"):
        return use.op
    return f"{use.op} {_value(use.value)}"


def _tolerance(use: GuideUse) -> str:
    if use.tolerance is None:
        return "-"
    text = (
        _value(use.tolerance)
        if not isinstance(use.tolerance, dict)
        else (f"{use.tolerance['relative']:g} x the threshold")
    )
    return f"{text}, {use.on_miss}" if use.on_miss else text


def _uses(uses: Iterable[GuideUse]) -> list[str]:
    rows = [
        "| Intent | Criterion | Mode | Near-miss band | How to combine it |",
        "|---|---|---|---|---|",
    ]
    for u in uses:
        cells = [u.intent, f"`{criterion_text(u)}`", u.mode, _tolerance(u), u.note or "-"]
        rows.append("| " + " | ".join(_cell(c) for c in cells) + " |")
    return rows


def _entry(e: FieldGuideEntry) -> list[str]:
    lines = [f"### `{e.name}`", "", f"**How to read it.** {e.reads}", ""]
    if e.uses:
        lines += ["**The criterion per intent**", "", *_uses(e.uses), ""]
    if e.caveats:
        lines += ["**When the reading lies**", "", *[f"- {c}" for c in e.caveats], ""]
    if e.sources:
        lines += ["Sources: " + "; ".join(e.sources), ""]
    return lines


def _anchor(text: str) -> str:
    return "".join(ch for ch in text.lower().replace(" ", "-") if ch.isalnum() or ch == "-")


def render(guide: FieldGuideSettings) -> str:
    """The whole page: a contents line, the fields by theme (first appearance order, file
    order within), the situations."""
    themes: dict[str, list[FieldGuideEntry]] = {}
    for e in guide.fields:
        themes.setdefault(e.theme, []).append(e)
    lines = [HEADER]
    if themes:
        contents = " · ".join(f"[{t.capitalize()}](#{_anchor(t)})" for t in themes)
        lines += [f"{len(guide.fields)} fields: {contents}.", ""]
    for theme, entries in themes.items():
        lines += [f"## {theme.capitalize()}", ""]
        for e in entries:
            lines += _entry(e)
    if guide.situations:
        lines += ["## Situations that fool several thresholds", ""]
        for s in guide.situations:
            affects = ", ".join(f"`{f}`" for f in s.affects)
            lines += [
                f"### {s.name.capitalize()}",
                "",
                f"**Signs.** {s.signs}",
                "",
                f"**Affects.** {affects}",
                "",
                f"**What to do.** {s.do}",
                "",
            ]
    return "\n".join(lines).rstrip() + "\n"
