"""Render the field guide pages from the site field guide (``config/site/field_guide/*.toml``,
ADR 0041 amended): the index ``docs/data/field-guide.md`` (how to read the guide, the themes
with their field counts, the situations that fool several thresholds) and one page per theme
under ``docs/data/field-guide/`` (each field with how to read it, a table of the usual
criterion per intent, the caveats and the sources; a page stays under the file-length cap
because a theme does). ``make features-doc`` writes them next to the catalogue;
``tests/architecture/test_features.py`` keeps them up to date."""

import json
from collections.abc import Iterable

from algotrade.config.site.field_guide import FieldGuideEntry, FieldGuideSettings, GuideUse

PATH = "docs/data/field-guide.md"
DIR = "docs/data/field-guide"
SOURCE = "config/site/field_guide/"

HEADER = f"""# Field guide: how to read the catalogue's fields

Generated by `make features-doc` from `{SOURCE}` (one file per theme); edit those, not this page.
The same guide is shown by the Builder with each field and sent to the text model that drafts
a screen from a sentence (ADR 0041), so a threshold a person reads here is the threshold the
model proposes.

Every field is read the same way: **how to read it** (what low and high mean, in the field's
unit: a decimal field takes 0.10 for 10%), **the criterion per intent** (what a trader wants,
and the rule-screen criterion that expresses it: the operator, the value, the mode and the
near-miss band of [rules.md](../screeners/rules.md); `hard` rejects a miss, `soft` keeps a
near miss as a WATCH or a risk, `score` only ranks), and **when the reading lies**: the
situations in which the number is right and the conclusion is wrong, each with the field
that exposes it. The fields are on one page per theme (below). The
[situations](#situations-that-fool-several-thresholds) at the end of this page are the
ones that distort many fields at once; a screen that ignores them finds the same false
positives whatever its thresholds. A null never passes a `hard` criterion (missing data never
passes); a field's own catalogue entry ([features.md](features.md)) says when it is null.
"""


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def _value(value: object) -> str:
    return json.dumps(value)


def criterion_text(use: GuideUse) -> str:
    """``op value`` as a person reads it (``is_null`` and ``not_null`` take no value)."""
    if use.op in ("is_null", "not_null"):
        return use.op
    return f"{use.op} {_value(use.value)}"


def _tolerance(use: GuideUse) -> str:
    if use.tolerance is None:
        return "-"
    text = (
        _value(use.tolerance)
        if not isinstance(use.tolerance, dict)
        else (f"{use.tolerance['relative']:g} x the threshold")
    )
    return f"{text}, {use.on_miss}" if use.on_miss else text


def _uses(uses: Iterable[GuideUse]) -> list[str]:
    rows = [
        "| Intent | Criterion | Mode | Near-miss band | How to combine it |",
        "|---|---|---|---|---|",
    ]
    for u in uses:
        cells = [u.intent, f"`{criterion_text(u)}`", u.mode, _tolerance(u), u.note or "-"]
        rows.append("| " + " | ".join(_cell(c) for c in cells) + " |")
    return rows


def _entry(e: FieldGuideEntry) -> list[str]:
    lines = [f"### `{e.name}`", "", f"**How to read it.** {e.reads}", ""]
    if e.uses:
        lines += ["**The criterion per intent**", "", *_uses(e.uses), ""]
    if e.caveats:
        lines += ["**When the reading lies**", "", *[f"- {c}" for c in e.caveats], ""]
    if e.sources:
        lines += ["Sources: " + "; ".join(e.sources), ""]
    return lines


def _anchor(text: str) -> str:
    return "".join(ch for ch in text.lower().replace(" ", "-") if ch.isalnum() or ch == "-")


def _themes(guide: FieldGuideSettings) -> dict[str, list[FieldGuideEntry]]:
    """The entries by theme, themes in first appearance order, file order within."""
    themes: dict[str, list[FieldGuideEntry]] = {}
    for e in guide.fields:
        themes.setdefault(e.theme, []).append(e)
    return themes


def theme_path(theme: str) -> str:
    """The theme's page: ``docs/data/field-guide/<slug>.md``."""
    return f"{DIR}/{_anchor(theme)}.md"


def render(guide: FieldGuideSettings) -> str:
    """The index page: the header, the themes (a link to each page with its field count) and
    the situations."""
    themes = _themes(guide)
    lines = [HEADER]
    if themes:
        lines += [f"## Themes ({len(guide.fields)} fields)", ""]
        for theme, entries in themes.items():
            link = theme_path(theme).removeprefix("docs/data/")
            names = ", ".join(f"`{e.name}`" for e in entries)
            lines += [f"- [{theme.capitalize()}]({link}) ({len(entries)}): {names}"]
        lines.append("")
    if guide.situations:
        lines += ["## Situations that fool several thresholds", ""]
        for s in guide.situations:
            affects = ", ".join(f"`{f}`" for f in s.affects)
            lines += [
                f"### {s.name.capitalize()}",
                "",
                f"**Signs.** {s.signs}",
                "",
                f"**Affects.** {affects}",
                "",
                f"**What to do.** {s.do}",
                "",
            ]
    return "\n".join(lines).rstrip() + "\n"


def render_theme(theme: str, entries: Iterable[FieldGuideEntry]) -> str:
    """One theme's page: its fields in file order."""
    lines = [
        f"# Field guide: {theme}",
        "",
        f"Generated by `make features-doc` from `{SOURCE}`; edit those files, not this page. "
        "How to read the guide, and the situations that fool several thresholds: "
        "[field-guide.md](../field-guide.md).",
        "",
    ]
    for e in entries:
        lines += _entry(e)
    return "\n".join(lines).rstrip() + "\n"


def pages(guide: FieldGuideSettings) -> dict[str, str]:
    """Every page by repository path: the index, then one per theme."""
    out = {PATH: render(guide)}
    for theme, entries in _themes(guide).items():
        out[theme_path(theme)] = render_theme(theme, entries)
    return out
